// Code generated by "requestgen -type NoParamRequest -url /v1/bullet -method GET -debug ./example/api"; DO NOT EDIT.

package api

import (
	"context"
	"net/url"
)

func (n *NoParamRequest) Do(ctx context.Context) (interface{}, error) {

	// no body params
	var params interface{}
	query := url.Values{}

	req, err := n.client.NewRequest(ctx, "GET", "/v1/bullet", query, params)
	if err != nil {
		return nil, err
	}

	response, err := n.client.SendRequest(req)
	if err != nil {
		return nil, err
	}

	var apiResponse interface{}
	if err := response.DecodeJSON(&apiResponse); err != nil {
		return nil, err
	}
	return &apiResponse, nil
}
