// Code generated by "requestgen -type QueryOrderRequest -responseType .Response -responseDataField Data -responseDataType []Order"; DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"net/url"
	"reflect"
	"regexp"
)

func (q *QueryOrderRequest) Id(id []int) *QueryOrderRequest {
	q.id = id
	return q
}

func (q *QueryOrderRequest) AddId(id ...int) *QueryOrderRequest {
	q.id = append(q.id, id...)
	return q
}

// GetQueryParameters builds and checks the query parameters and returns url.Values
func (q *QueryOrderRequest) GetQueryParameters() (url.Values, error) {
	var params = map[string]interface{}{}
	// check id field -> json key id
	id := q.id

	// TEMPLATE check-required
	// END TEMPLATE check-required

	// assign parameter of id
	params["id"] = id

	query := url.Values{}
	for _k, _v := range params {
		if q.isVarSlice(_v) {
			q.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParameters builds and checks the parameters and return the result in a map object
func (q *QueryOrderRequest) GetParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}

	return params, nil
}

// GetParametersQuery converts the parameters from GetParameters into the url.Values format
func (q *QueryOrderRequest) GetParametersQuery() (url.Values, error) {
	query := url.Values{}

	params, err := q.GetParameters()
	if err != nil {
		return query, err
	}

	for _k, _v := range params {
		if q.isVarSlice(_v) {
			q.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParametersJSON converts the parameters from GetParameters into the JSON format
func (q *QueryOrderRequest) GetParametersJSON() ([]byte, error) {
	params, err := q.GetParameters()
	if err != nil {
		return nil, err
	}

	return json.Marshal(params)
}

// GetSlugParameters builds and checks the slug parameters and return the result in a map object
func (q *QueryOrderRequest) GetSlugParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}

	return params, nil
}

func (q *QueryOrderRequest) applySlugsToUrl(url string, slugs map[string]string) string {
	for _k, _v := range slugs {
		needleRE := regexp.MustCompile(":" + _k + "\\b")
		url = needleRE.ReplaceAllString(url, _v)
	}

	return url
}

func (q *QueryOrderRequest) iterateSlice(slice interface{}, _f func(it interface{})) {
	sliceValue := reflect.ValueOf(slice)
	for _i := 0; _i < sliceValue.Len(); _i++ {
		it := sliceValue.Index(_i).Interface()
		_f(it)
	}
}

func (q *QueryOrderRequest) isVarSlice(_v interface{}) bool {
	rt := reflect.TypeOf(_v)
	switch rt.Kind() {
	case reflect.Slice:
		return true
	}
	return false
}

func (q *QueryOrderRequest) GetSlugsMap() (map[string]string, error) {
	slugs := map[string]string{}
	params, err := q.GetSlugParameters()
	if err != nil {
		return slugs, nil
	}

	for _k, _v := range params {
		slugs[_k] = fmt.Sprintf("%v", _v)
	}

	return slugs, nil
}
